### ISSUE TITLE
Question about the gaps

### ISSUE THREAD

**Issue by ArashPartow** [JamesBremner/so79276745#1]
Nice little project you've got there.  I have some suggestions pertaining about the optimality of the gaps.

![gaps_20241217](https://github.com/user-attachments/assets/ae951e37-fbe6-4c4f-bb83-f00318ee4d13)

**Gap1:** I think the two smaller boxes on the left could be dropped down to fill in the gap. Looking at the code it seems to follow the level set by the box on the right. Perhaps once the packing is done or after stages you could do a little tetris like clean-up step where you see if one or more boxes can be either moved up or down to reduce gaps

**Gap2:** Here the smaller piece at the tip of the arrow could be swapped with the two stacked pieces on its left

**Gap3:** The larger piece should be rotated 90degs and the two pieces just under the arrow could then be fit to its right and the two pieces on its right currently can be placed just under it.

**Comment by JamesBremner** [comment]
> Gap1: I think the two smaller boxes on the left could be dropped down to fill in the gap. Looking at the code it seems to follow the level set by the box on the right.

That would create a smaller gap above them.

> Gap2: Here the smaller piece at the tip of the arrow could be swapped with the two stacked pieces on its left

The complexity of the code required to recognize such an opportunity is unlikely to be worthwhile.  If you have an an idea of an algorithm to achieve this simply, please post it.

> Gap3: The larger piece should be rotated

Rotations are not allowed.

>  Perhaps once the packing is done or after stages you could do a little tetris like clean-up step where you see if one or more boxes can be either moved up or down to reduce gaps

It is an idea.  But code to do that would be complex.  If you have an an idea of an algorithm to achieve this simply, please post it.

On these occasions, I always enjoy posting this old cartoon

![image](https://github.com/user-attachments/assets/bb979a75-7236-477e-aeb5-14b477e74c8e)

**Comment by JamesBremner** [comment]
No response!  

OK, I will close this.
